### ISSUE TITLE
Calculate normal vectors for spheres

### ISSUE THREAD

**Issue by akosgarai** [akosgarai/go_opengl_playground#36]
It would be nice, if the cube with materials and light application is is implemented with spheres also.

## Tasks

- [x] Sphere has to be extended with the rotation feature (angle, axis)
- [x] Sphere has to be extended with the draw mode feature
- [x] Sphere has to be extended with the material feature
- [x] Sphere has to be extended with the direction getter function
- [x] Example application with the spheres
