### ISSUE TITLE
Lighting map example application

### ISSUE THREAD

**Issue by akosgarai** [akosgarai/go_opengl_playground#39]
based on [this](https://learnopengl.com/Lighting/Lighting-maps) tutorial.

## Tasks

- [x] get the texture images.
- [x] vertex shader for the light source sphere - could be same as i used in the 08 apps.
- [x] shaders for the textured cubes
- [x] write new application
