### ISSUE TITLE
Implement models

### ISSUE THREAD

**Issue by akosgarai** [akosgarai/go_opengl_playground#55]
The purpose of this implementation: Connect different meshes together (eg: the bug with body, eyes, back).

https://learnopengl.com/Model-Loading/Model

https://github.com/tbogdala/assimp-go - might be interesting assimp implementation

https://github.com/udhos/gwob - other solution <- I decided to use this one.

## Tasks

- [x] Implement a basic application that uses gwob to load meshes from file. - use the gwob example. 
- [x] Implement an application that uses other input file than the gwob example.
- [x] Extend model to be able to define composite meshes (eg, the bug)

## Update

The gwob pkg seems to be incomplete, so that, the model file reading and stuff is postponed.
The task has been changed to apply the model packages everywhere. 

Further tasks:

- [x] Export function to models - generate `.obj`, `.mat` files
- [x] Make the same images from the generated files.
- [x] Extend my gwob pkg, to fulfill my needs.
- [x] Create a PR to the orig gwob repo, if merged, use that one instead of my.

**Comment by akosgarai** [comment]
for the further improvements check #67

**Comment by akosgarai** [comment]
with the merge of #73 it is done.
