### ISSUE TITLE
ColorMesh should contain the color in a variable

### ISSUE THREAD

**Issue by akosgarai** [akosgarai/go_opengl_playground#59]
For creating a color mesh, we give the color input to the input generator function, not to the color mesh. It makes the export process difficult. To handle this, i want to administrate the color in a new variable. (could be called 'color').

## Tasks

- [ ] Update mesh & the tests for it.
- [ ] Update the related packages.
- [ ] Update the related applications.
