### ISSUE TITLE
Make the street lamp model scalable

### ISSUE THREAD

**Issue by akosgarai** [akosgarai/go_opengl_playground#86]
Currently the size of that model is hardcoded. I want to make it scaled with an input.
Update on the task. The rotation issue has to be resolved to make the scaling works properly. 

## Tasks

- [x] Mesh update - add YPR to the structure
- [x] Rotate function has to update the YPR values
- [x] Eliminate the rotation angel and axis setter getter functions
- [x] Make sure the applications are working well. - refactor the code if necessary.
- [x] Make sure that the documentation is still valid. - Update it if necessary.

**Comment by akosgarai** [comment]
As i see now, the rotation transformation is still buggy. Now i'm thinking about a refactor of the meshes. Instead of storing the rotation angle and axis, i should maintain a rotation matrix. It will resolve the calculation of the new rotation angle and axis. (Currently it's totally missing.)

**Comment by akosgarai** [comment]
Other idea: store the euler angles (yaw pitch roll) and use them for calculating the rotation matrix. Pros for this, the rotation logic could be easily managed, the calculations could be skipped.
