### ISSUE TITLE
Texture orientation option

### ISSUE THREAD

**Issue by akosgarai** [akosgarai/go_opengl_playground#90]
I want to manage the orientation of the textures on a cube. Example: a door, that contains a handle. the handle supposed to be on the same position on the opposite side.

## Tasks

Cuboid as pilot - first refactor it

- [x] Make it more testable, like the cylinder. 
- [x] separate textured and material mesh inputs, fix broken applications.
- [x] - implement the feature, update room model, door supposed to be fine.

## Orientations:

- default - as it is now
- opposite side same - it should be used for the door.
